application: mboilerplate
version: production
# module: default
runtime: python27
api_version: 1
threadsafe: true
# instance_class: F1
# F1  128 MB  600 Mhz $0.05 (default)
# F2  256 MB  1.2 Ghz $0.10
# F4  512 MB  2.4 Ghz $0.20
# F4_1G 1024 MB 2.4 Ghz $0.30
# automatic_scaling:
#   min_idle_instances: 5
#   max_idle_instances: automatic  # default value
#   min_pending_latency: 30ms  # default value
#   max_pending_latency: automatic
#   max_concurrent_requests: 50

env_variables:
  theme: 'default'
  #https://cloud.google.com/appengine/docs/python/cloud-sql/
  # CLOUDSQL_CONNECTION_NAME: <app_id>:us-central1:<db_instance>
  # CLOUDSQL_DB: <db_name>
  # CLOUDSQL_USER: <db_user>
  # CLOUDSQL_PASSWORD: <db_password>

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py

builtins:
- appstats: on #/_ah/stats/
- remote_api: on #/_ah/remote_api/

handlers:
# @bp_admin
- url: /admin.*
  script: main.app
  login: admin

# seo
- url: /(robots\.txt|humans\.txt|sitemap\.xml|crossdomain\.xml)
  script: main.app

# mobile enhancer
- url: /manifest.json
  static_files: bp_content/themes/default/templates/seo/manifest.json
  upload: bp_content/themes/default/templates/seo/manifest.json

# @bp_includes - materializeCSS
- url: /materializecss
  static_dir: bp_includes/static/materializecss

# @bp_content - default theme statics
- url: /default/materialize
  static_dir: bp_content/themes/default/static/materialize

# @taskqueue email sender
- url: /taskqueue-send-email.*
  script: main.app
  login: admin

# endpoints handler: this must be /_ah/spi for endpoints
- url: /_ah/spi/.*
  script: api.APPLICATION

# main
- url: /.*
  script: main.app
#  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0
- name: MySQLdb
  version: "latest"

error_handlers:
  # Only errors with error_code, don't put a default error here
  - error_code: over_quota
    file: bp_content/themes/default/errors/over_quota.html

  - error_code: dos_api_denial
    file: bp_content/themes/default/errors/dos_api_denial.html

  - error_code: timeout
    file: bp_content/themes/default/errors/timeout.html
    
inbound_services:
- mail_bounce
- mail
